# Personalize your website info here
title:            Jan-Erik Hoffmann
tagline:          'Professional Website for Jan-Erik Hoffmann'
description:      'Website and Blog for Jan-Erik Hoffmann'
url:              http://ElEriko.github.io
author:
  name:           'Jan-Erik Hoffmann'
  url:            https://twitter.com/anewguy

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
